/*
 * Copyright (C) 2015 Juan Silva <juanssl@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.tuxedoberries.transformo.data.generator;

import java.util.ArrayList;
import java.util.List;
import org.tuxedoberries.transformo.data.RowData;
import org.tuxedoberries.transformo.data.TableMeta;

/**
 *
 * @author Juan Silva
 */
public abstract class BaseGenerator {

    protected List<DataPack> _data;

    /**
     * Initialize this instance
     */
    public BaseGenerator() {
        _data = new ArrayList<DataPack>();
    }

    /**
     * Add the Table Meta and a list of Data in the table format.
     *
     * @param meta
     * @param data
     */
    public void addData(TableMeta meta, List<RowData> data) {
        _data.add(new DataPack(meta, data));
    }

    /**
     * Add data to generate
     *
     * @param data
     */
    public void addData(DataPack data) {
        _data.add(data);
    }

    /**
     * Set the data to generate.
     *
     * @param data
     */
    public void setData(List<DataPack> data) {
        _data = data;
    }

    /**
     * Generate the data in the specific format.
     */
    public abstract void generate();

    /**
     * Gets the data generated by Generate as a String
     *
     * @return
     */
    public abstract String getData();

}
